#!/bin/bash

# Define noticen path
MYPATH="${HOME}/.local/noticen"

# Import sounds
. "${MYPATH}/sounds.import"

hide_noticen="$2"

turn_on () {
    ln -fs -T "${FDTSOUNDS}" "${SYSOUNDS}"
    [[ $hide_noticen == "hide" ]] || noticen --sysound on
}

turn_off () {
    rm "$SYSOUNDS"
    [[ $hide_noticen == "hide" ]] || noticen --sysound off
}

is_on () {
    [[ -e $SYSOUNDS ]]
}

case "$1" in
    "--toggle")
        if is_on; then
            turn_off
        else
            turn_on
        fi
    ;;
    "--on") ! is_on && turn_on
    ;;
    "--off") is_on && turn_off
    ;;
esac

